version: '1'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"