version: '1'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"